package br.com.unit.fisicoquimica;
import br.com.unit.fisicoquimica.calculos.TemperaturaService;import br.com.unit.fisicoquimica.colorimetria.ColorimetriaService;import br.com.unit.fisicoquimica.dados.EstatisticaService;import br.com.unit.fisicoquimica.dados.MedicaoExperimental;import br.com.unit.fisicoquimica.decaimento.DecaimentoNuclearService;import br.com.unit.fisicoquimica.reacao.ReacaoService;import org.junit.jupiter.api.Test;import java.util.List;import static org.junit.jupiter.api.Assertions.*;
class RegrasMatematicasTest {
 @Test void temperaturaEValidacoes(){var s=new TemperaturaService();assertEquals(273.15,s.celsiusParaKelvin(0),1e-9);assertEquals(373.15,s.celsiusParaKelvin(100),1e-9);assertEquals(0,s.kelvinParaCelsius(273.15),1e-9);assertEquals(-273.15,s.kelvinParaCelsius(0),1e-9);assertThrows(IllegalArgumentException.class,()->s.kelvinParaCelsius(-.01));assertThrows(IllegalArgumentException.class,()->s.celsiusParaKelvin(-274));}
 @Test void taxaSimplificada(){var s=new ReacaoService();assertEquals(.1,s.calcularTaxa(10),1e-9);assertEquals(.25,s.calcularTaxa(4),1e-9);assertThrows(IllegalArgumentException.class,()->s.calcularTaxa(0));assertThrows(IllegalArgumentException.class,()->s.calcularTaxa(-1));}
 @Test void decaimentoEserie(){var s=new DecaimentoNuclearService();assertEquals(100,s.calcularQuantidade(100,10,0),1e-9);assertEquals(50,s.calcularQuantidade(100,10,10),1e-9);assertEquals(25,s.calcularQuantidade(100,10,20),1e-9);assertEquals(12.5,s.calcularQuantidade(100,10,30),1e-9);var pontos=s.simular(100,10,30,4);assertEquals(4,pontos.size());assertTrue(pontos.stream().allMatch(p->p.quantidade()<=100));for(int x=1;x<pontos.size();x++)assertTrue(pontos.get(x).quantidade()<=pontos.get(x-1).quantidade());assertThrows(IllegalArgumentException.class,()->s.calcularQuantidade(-1,10,0));assertThrows(IllegalArgumentException.class,()->s.calcularQuantidade(1,0,0));assertThrows(IllegalArgumentException.class,()->s.calcularQuantidade(1,1,-1));}
 @Test void colorimetriaEValidacoes(){var s=new ColorimetriaService();assertEquals(1,s.calcularAbsorbancia(100,10),1e-9);assertEquals(0,s.calcularAbsorbancia(100,100),1e-9);assertEquals(.30103,s.calcularAbsorbancia(100,50),1e-5);assertThrows(IllegalArgumentException.class,()->s.calcularAbsorbancia(0,1));assertThrows(IllegalArgumentException.class,()->s.calcularAbsorbancia(1,0));}
 @Test void estatisticaEValidacoes(){var s=new EstatisticaService();var r=s.calcular(List.of(new MedicaoExperimental(0,1),new MedicaoExperimental(1,2),new MedicaoExperimental(2,3),new MedicaoExperimental(3,4),new MedicaoExperimental(4,5)));assertEquals(5,r.quantidade());assertEquals(3,r.media(),1e-9);assertEquals(1,r.minimo(),1e-9);assertEquals(5,r.maximo(),1e-9);var unico=s.calcular(List.of(new MedicaoExperimental(0,10)));assertEquals(10,unico.media(),1e-9);assertThrows(IllegalArgumentException.class,()->s.calcular(List.of()));}
}
